`timescale 1ns / 1ps

//==============================================================================
// Testbench: tb_systolic_array_golden
// Purpose:    File-based golden model verification.
//
//             Reads A.txt / B.txt (generated by golden_model.py --generate),
//             drives the systolic_array DUT tile-by-tile, reads back results
//             from result BRAM, and writes them to rtl_results.txt in the
//             "<row> <col> <value>" format expected by:
//
//               python scripts/golden_model.py --compare rtl_results.txt
//
// Architecture:
//   - K_DEPTH=1 (standard matmul mode: one activation per PE row, weights
//     are stationary so K-reduction happens across ROWS, not K_DEPTH)
//   - Single tile: M=ROWS, N=COLS, K=ROWS (no tiling needed)
//   - For each output row m:
//       1. Load weights W[r][c] = B[r][c]  (same for all m, reloaded each time)
//       2. Preload activations A_hw[r][0] = A[m][r] into act_bram
//       3. Run systolic_array (WEIGHT_LOAD → COMPUTE → READOUT → SERIALIZE)
//       4. Read last capture row from res_bram: addr = (ROWS-1)*COLS + c
//       5. Write "m c result" to rtl_results.txt
//
// Usage (run from project root):
//   1. python scripts/golden_model.py --generate --M 4 --N 4 --K 4
//   2. xvlog -sv src/*.sv src/*.v tb/tb_systolic_array_golden.sv
//   3. xelab -debug typical tb_systolic_array_golden
//   4. xsim tb_systolic_array_golden -runall
//   5. python scripts/golden_model.py --compare rtl_results.txt
//
// Or use the helper script:
//   powershell -File sim/batch/run_golden.ps1
//==============================================================================

module tb_systolic_array_golden;

    localparam ROWS        = 4;
    localparam COLS        = 4;
    localparam DATA_WIDTH  = 16;
    localparam ACCUM_WIDTH = 40;
    localparam K_DEPTH     = 4;      // HW requires K_DEPTH>=2 (act_deserializer $clog2)
                                      // Standard matmul: only slot 0 filled, rest = 0
    localparam BUF_ADDR_W  = 8;
    localparam WT_ADDR_W   = 4;
    localparam CLK_PERIOD  = 10;

    // Matrix dimensions (single tile: M=ROWS, N=COLS, K=ROWS)
    localparam M_DIM = 4;
    localparam N_DIM = 4;
    localparam K_DIM = 4;

    reg                                 clk, rst_n;
    reg                                 start;
    wire                                busy, done;
    reg                                 use_bram_act;

    reg  [DATA_WIDTH-1:0]               weight_data;
    wire                                weight_ready;
    reg  [DATA_WIDTH-1:0]               act_data [0:ROWS-1];
    reg                                 act_valid;
    reg                                 act_wr_en;
    reg  [BUF_ADDR_W-1:0]               act_wr_addr;
    reg  [DATA_WIDTH-1:0]               act_wr_data;
    wire [ACCUM_WIDTH-1:0]              result_data [0:COLS-1];
    wire                                result_valid;
    reg                                 res_rd_en;
    reg  [BUF_ADDR_W-1:0]               res_rd_addr;
    wire [ACCUM_WIDTH-1:0]              res_rd_data;
    reg  [BUF_ADDR_W-1:0]               act_base_addr, res_base_addr;

    systolic_array #(
        .ROWS(ROWS), .COLS(COLS), .DATA_WIDTH(DATA_WIDTH),
        .ACCUM_WIDTH(ACCUM_WIDTH), .K_DEPTH(K_DEPTH),
        .BUF_ADDR_W(BUF_ADDR_W), .BUF_DEPTH(256), .WT_ADDR_W(WT_ADDR_W)
    ) u_dut (
        .clk(clk), .rst_n(rst_n),
        .start(start), .weight_preloaded(1'b0), .prefetch_start(1'b0),
        .busy(busy), .done(done),
        .use_bram_act(use_bram_act), .weight_data(weight_data),
        .weight_ready(weight_ready), .act_data(act_data), .act_valid(act_valid),
        .act_wr_en(act_wr_en), .act_wr_addr(act_wr_addr), .act_wr_data(act_wr_data),
        .result_data(result_data), .result_valid(result_valid),
        .res_rd_en(res_rd_en), .res_rd_addr(res_rd_addr), .res_rd_data(res_rd_data),
        .act_base_addr(act_base_addr), .res_base_addr(res_base_addr)
    );

    always #(CLK_PERIOD/2) clk = ~clk;

    //==========================================================================
    // Task: Load weights during WEIGHT_LOAD phase
    //==========================================================================
    task automatic load_weights;
        input signed [DATA_WIDTH-1:0] w_mat [0:ROWS-1][0:COLS-1];
        integer r, c;
        begin
            while (!weight_ready) @(posedge clk);
            for (r = 0; r < ROWS; r = r + 1)
                for (c = 0; c < COLS; c = c + 1) begin
                    weight_data = w_mat[r][c];
                    @(posedge clk);
                end
            weight_data = 0;
        end
    endtask

    //==========================================================================
    // Task: Preload activations into act_bram (row-major, K_DEPTH slots per row)
    //   BRAM layout: addr = base + r*K_DEPTH + k
    //   For standard matmul: slot 0 = A[m][r], slots 1..K_DEPTH-1 = 0
    //   (weights are stationary, so only slot 0 contributes to the result)
    //==========================================================================
    task automatic preload_act;
        input [BUF_ADDR_W-1:0] base;
        input signed [DATA_WIDTH-1:0] a_vec [0:ROWS-1];
        integer r, k, addr;
        begin
            addr = base;
            for (r = 0; r < ROWS; r = r + 1) begin
                for (k = 0; k < K_DEPTH; k = k + 1) begin
                    @(posedge clk);
                    act_wr_en   <= 1;
                    act_wr_addr <= addr;
                    // Slot 0: activation value; slots 1..K_DEPTH-1: zero
                    act_wr_data <= (k == 0) ? a_vec[r] : 16'sd0;
                    addr = addr + 1;
                end
            end
            @(posedge clk); act_wr_en <= 0; act_wr_addr <= 0; act_wr_data <= 0;
        end
    endtask

    //==========================================================================
    // Task: Read a single result BRAM entry (3 cycles: issue, wait, capture)
    //==========================================================================
    task automatic read_res;
        input  [BUF_ADDR_W-1:0]   addr;
        output [ACCUM_WIDTH-1:0]  val;
        begin
            @(posedge clk); res_rd_en <= 1; res_rd_addr <= addr;
            @(posedge clk); res_rd_en <= 0; res_rd_addr <= 0;
            @(posedge clk); val = res_rd_data;
        end
    endtask

    //==========================================================================
    // Task: Run a BRAM-path tile computation
    //==========================================================================
    task automatic run_tile;
        input signed [DATA_WIDTH-1:0] w_mat [0:ROWS-1][0:COLS-1];
        input signed [DATA_WIDTH-1:0] a_vec [0:ROWS-1];
        input [BUF_ADDR_W-1:0] act_base, res_base;
        begin
            use_bram_act  <= 1;
            act_base_addr <= act_base;
            res_base_addr <= res_base;
            preload_act(act_base, a_vec);
            @(posedge clk); start <= 1; @(posedge clk); start <= 0;
            load_weights(w_mat);
            act_valid <= 0;
            while (!done) @(posedge clk);
            @(posedge clk);
        end
    endtask

    //==========================================================================
    // Matrix storage (read from files)
    //==========================================================================
    reg signed [DATA_WIDTH-1:0] A_mat [0:M_DIM-1][0:K_DIM-1];
    reg signed [DATA_WIDTH-1:0] B_mat [0:K_DIM-1][0:N_DIM-1];

    // Tile-local arrays
    reg signed [DATA_WIDTH-1:0] w_tile [0:ROWS-1][0:COLS-1];
    reg signed [DATA_WIDTH-1:0] a_tile [0:ROWS-1];

    integer fd, fd_out, scan_result;
    integer m, r, c, k;
    reg [ACCUM_WIDTH-1:0] rv;

    //==========================================================================
    // Main
    //==========================================================================
    initial begin
        // Init
        clk = 0; rst_n = 0; start = 0; use_bram_act = 0;
        weight_data = 0; act_valid = 0;
        for (int i = 0; i < ROWS; i++) act_data[i] = 0;
        act_wr_en = 0; act_wr_addr = 0; act_wr_data = 0;
        res_rd_en = 0; res_rd_addr = 0; act_base_addr = 0; res_base_addr = 0;

        $display("============================================================");
        $display("tb_systolic_array_golden: File-based golden verification");
        $display("  Config: ROWS=%0d COLS=%0d K_DEPTH=%0d  Matrix: %0dx%0dx%0d",
                 ROWS, COLS, K_DEPTH, M_DIM, N_DIM, K_DIM);
        $display("============================================================");

        //------------------------------------------------------------------
        // Read A.txt
        //------------------------------------------------------------------
        fd = $fopen("test_vectors/A.txt", "r");
        if (fd == 0) begin
            $display("ERROR: Cannot open test_vectors/A.txt");
            $display("       Run: python scripts/golden_model.py --generate --M 4 --N 4 --K 4");
            $finish;
        end
        for (m = 0; m < M_DIM; m = m + 1)
            for (k = 0; k < K_DIM; k = k + 1)
                scan_result = $fscanf(fd, "%d", A_mat[m][k]);
        $fclose(fd);
        $display("  Loaded A (%0dx%0d) from test_vectors/A.txt", M_DIM, K_DIM);

        //------------------------------------------------------------------
        // Read B.txt
        //------------------------------------------------------------------
        fd = $fopen("test_vectors/B.txt", "r");
        if (fd == 0) begin
            $display("ERROR: Cannot open test_vectors/B.txt");
            $finish;
        end
        for (k = 0; k < K_DIM; k = k + 1)
            for (c = 0; c < N_DIM; c = c + 1)
                scan_result = $fscanf(fd, "%d", B_mat[k][c]);
        $fclose(fd);
        $display("  Loaded B (%0dx%0d) from test_vectors/B.txt", K_DIM, N_DIM);

        //------------------------------------------------------------------
        // Reset
        //------------------------------------------------------------------
        repeat(8) @(posedge clk); rst_n = 1; repeat(2) @(posedge clk);

        //------------------------------------------------------------------
        // Build weight tile: W[r][c] = B[r][c]
        //   (K_DIM = ROWS, N_DIM = COLS → single tile)
        //------------------------------------------------------------------
        for (r = 0; r < ROWS; r = r + 1)
            for (c = 0; c < COLS; c = c + 1)
                w_tile[r][c] = B_mat[r][c];

        //------------------------------------------------------------------
        // Open output file
        //------------------------------------------------------------------
        fd_out = $fopen("rtl_results.txt", "w");
        if (fd_out == 0) begin
            $display("ERROR: Cannot open rtl_results.txt for writing");
            $finish;
        end

        $display("\n  Running %0d tiles (one per output row)...\n", M_DIM);

        //------------------------------------------------------------------
        // For each output row m:
        //   Load activations A[m][r] into BRAM
        //   Run systolic_array
        //   Read last capture row from res_bram
        //   Write "m c value" to rtl_results.txt
        //------------------------------------------------------------------
        for (m = 0; m < M_DIM; m = m + 1) begin
            // Activation vector for this row: A_hw[r][0] = A[m][r]
            for (r = 0; r < ROWS; r = r + 1)
                a_tile[r] = A_mat[m][r];

            // Run tile (reuse base addresses — each run overwrites)
            run_tile(w_tile, a_tile, 8'd0, 8'd0);

            // Read last capture row: addr = (ROWS-1)*COLS + c
            $write("  C[%0d] = [", m);
            for (c = 0; c < COLS; c = c + 1) begin
                read_res(8'd0 + (ROWS - 1) * COLS + c, rv);
                $fdisplay(fd_out, "%0d %0d %0d", m, c, $signed(rv));
                if (c < COLS - 1) $write("%0d, ", $signed(rv));
                else              $write("%0d", $signed(rv));
            end
            $display("]");
        end

        $fclose(fd_out);

        $display("\n============================================================");
        $display("RTL results written to rtl_results.txt (%0d entries)", M_DIM * N_DIM);
        $display("Next: python scripts/golden_model.py --compare rtl_results.txt");
        $display("============================================================");
        $finish;
    end

    always @(posedge clk)
        if (done && rst_n) $display("    [MON] Time %0t: tile done", $time);

endmodule
